---
galaxy_info:
  author: Stephane ROBERT
  role_name: proxmox
  namespace: stephrobert
  description: Install Proxmox VE
  company: none
  license: MLP2
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bullseye
  galaxy_tags:
    - virtualization
dependencies: []